import {
  Basketball,
  Briefcase,
  Cpu,
  ForkKnife,
  GraduationCap,
  HandHeart,
  Handshake,
  HandsPraying,
  Heartbeat,
  Martini,
  MusicNotes,
  PaintBrush,
  type Icon,
} from '@phosphor-icons/react'

export type Category =
  | 'night-out'
  | 'education'
  | 'business'
  | 'music'
  | 'sports'
  | 'art-culture'
  | 'food-drink'
  | 'technology'
  | 'health-wellness'
  | 'community-social'
  | 'networking'
  | 'religion'

export const categories: Category[] = [
  'night-out',
  'education',
  'business',
  'music',
  'sports',
  'art-culture',
  'food-drink',
  'technology',
  'health-wellness',
  'community-social',
  'networking',
  'religion',
]

export const categoryMeta: Record<
  Category,
  { label: string; icon: Icon; color: string; soft: string; fg: string; subcategories: string[] }
> = {
  'night-out': {
    label: 'Night Out',
    icon: Martini,
    color: 'var(--color-cat-nightout)',
    soft: 'var(--color-cat-nightout-soft)',
    fg: 'var(--color-cat-nightout-fg)',
    subcategories: [
      'Comedy Shows',
      'Gigs',
      'Cinema',
      'Theater Performances',
      'Nightclubs',
      'Karaoke Nights',
      'Dinner Shows',
    ],
  },
  education: {
    label: 'Education',
    icon: GraduationCap,
    color: 'var(--color-cat-education)',
    soft: 'var(--color-cat-education-soft)',
    fg: 'var(--color-cat-education-fg)',
    subcategories: [
      'Seminars',
      'Hackathons',
      'Workshops',
      'Training Sessions',
      'Bootcamps',
      'Conferences',
      'Lectures',
      'Webinars',
      'Courses',
      'Masterclasses',
    ],
  },
  business: {
    label: 'Business',
    icon: Briefcase,
    color: 'var(--color-cat-business)',
    soft: 'var(--color-cat-business-soft)',
    fg: 'var(--color-cat-business-fg)',
    subcategories: [
      'Conferences',
      'Seminars',
      'Expos',
      'Product Launches',
      'Workshops',
      'Keynote Speeches',
    ],
  },
  music: {
    label: 'Music',
    icon: MusicNotes,
    color: 'var(--color-cat-music)',
    soft: 'var(--color-cat-music-soft)',
    fg: 'var(--color-cat-music-fg)',
    subcategories: [
      'Festivals',
      'Concerts',
      'Gigs',
      'Music Performances',
      'Live Music Events',
      'Dance Shows',
      'Acoustic Sessions',
      'Music Competitions',
    ],
  },
  sports: {
    label: 'Sports',
    icon: Basketball,
    color: 'var(--color-cat-sports)',
    soft: 'var(--color-cat-sports-soft)',
    fg: 'var(--color-cat-sports-fg)',
    subcategories: [
      'Marathons',
      'Football Matches',
      'Basketball Games',
      'Gym Memberships',
      'Fitness Classes',
      'Yoga Sessions',
      'Tennis Tournaments',
      'Boxing Matches',
      'Motorsports Events',
    ],
  },
  'art-culture': {
    label: 'Art & Culture',
    icon: PaintBrush,
    color: 'var(--color-cat-artculture)',
    soft: 'var(--color-cat-artculture-soft)',
    fg: 'var(--color-cat-artculture-fg)',
    subcategories: [],
  },
  'food-drink': {
    label: 'Food & Drink',
    icon: ForkKnife,
    color: 'var(--color-cat-fooddrink)',
    soft: 'var(--color-cat-fooddrink-soft)',
    fg: 'var(--color-cat-fooddrink-fg)',
    subcategories: [
      'Food Festivals',
      'Wine Tastings',
      'Cooking Classes',
      'Cocktail Workshops',
      'Restaurant Openings',
      'Culinary Tours',
      'Food Truck Events',
      'Brewery Tours',
      'Farmers Markets',
      'Cooking Competitions',
    ],
  },
  technology: {
    label: 'Technology',
    icon: Cpu,
    color: 'var(--color-cat-technology)',
    soft: 'var(--color-cat-technology-soft)',
    fg: 'var(--color-cat-technology-fg)',
    subcategories: [
      'Tech Conferences',
      'Hackathons',
      'Coding Bootcamps',
      'Startup Pitches',
      'Product Demos',
      'Robotics Competitions',
      'AI Workshops',
      'Cybersecurity Seminars',
      'IoT Expos',
      'VR/AR Experiences',
    ],
  },
  'health-wellness': {
    label: 'Health & Wellness',
    icon: Heartbeat,
    color: 'var(--color-cat-healthwellness)',
    soft: 'var(--color-cat-healthwellness-soft)',
    fg: 'var(--color-cat-healthwellness-fg)',
    subcategories: [
      'Fitness Workshops',
      'Yoga Retreats',
      'Meditation Classes',
      'Nutrition Seminars',
      'Wellness Conferences',
      'Health Screenings',
      'Mental Health Workshops',
      'Spa Events',
      'Mindfulness Retreats',
      'Self-care Sessions',
    ],
  },
  'community-social': {
    label: 'Community & Social',
    icon: HandHeart,
    color: 'var(--color-cat-communitysocial)',
    soft: 'var(--color-cat-communitysocial-soft)',
    fg: 'var(--color-cat-communitysocial-fg)',
    subcategories: [
      'Charity Events',
      'Fundraisers',
      'Volunteer Opportunities',
      'Community Gatherings',
      'Social Meetups',
      'Environmental Campaigns',
      'Cultural Celebrations',
    ],
  },
  networking: {
    label: 'Networking',
    icon: Handshake,
    color: 'var(--color-cat-networking)',
    soft: 'var(--color-cat-networking-soft)',
    fg: 'var(--color-cat-networking-fg)',
    subcategories: [
      'Networking Events',
      'Business Networking',
      'Speed Networking',
      'Mixers & Meetups',
      'Industry Meetups',
      'Alumni Networking',
    ],
  },
  religion: {
    label: 'Religion',
    icon: HandsPraying,
    color: 'var(--color-cat-religion)',
    soft: 'var(--color-cat-religion-soft)',
    fg: 'var(--color-cat-religion-fg)',
    subcategories: ['Retreat', 'Special Event'],
  },
}
